### ISSUE TITLE
dependency inversion

### ISSUE THREAD

**Issue by mlebkowski** [wildbit/swiftmailer-postmark#1]
refs: 9d3c7c84bacc0126da8cce9ac2b9deb067375fc8

You shouldn’t add this adapter to this repository, since it requires `Illuminate\*` classes that aren’t defined anywhere. The proper way would be to create `wildbit/laravel-postmark-provider` that require both `laravel/laravel` and this package and put it there.

More on that topic: http://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/

**Comment by atheken** [comment]
@mlebkowski This is good feedback! We'll look at splitting this out.

**Comment by atheken** [comment]
Thanks again for the suggestion @mlebkowski, we have split this out into a separate package as you suggested: https://github.com/wildbit/laravel-postmark-provider

**Comment by mlebkowski** [comment]
:+1:
