### ISSUE TITLE
Swift_Mime_Message is removed since 6.0

### ISSUE THREAD

**Issue by robinvdvleuten** [wildbit/swiftmailer-postmark#11]
When you install the transport in a newer Symfony project, it installs swiftmailer 6.0+ where the Swift_Mime_Message class is removed thus the following error occurs;

```php
PHP Warning:  Uncaught ReflectionException: Class Swift_Mime_Message not found in vendor/wildbit/swiftmailer-postmark/src/Postmark/Transport.php:10
```

**Comment by nateiler** [comment]
For what it's worth, I have a pull request #13 for Swift Mailer v6 support.  We'll use our 3.0 release`composer require flipboxdigital/swiftmailer-postmark` until the pull request is merged.

**Comment by ashgibson** [comment]
I've changed my dep over to flipboxdigital/swiftmailer-postmark until this is resolved. I would prefer to use the official lib so hopefully this is resolved soon.

**Comment by atheken** [comment]
Hey all. Closing this up, as I've just released version 3 of the transport with SwiftMailer 6 support.

Please let us know if you run into issues or have questions.
