### ISSUE TITLE
Swift Mailer 6 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [wildbit/swiftmailer-postmark#12]
Will this package be updated for Swift Mailer 6? (Released in May.)

Looks like the only thing you’d need to add is a `ping()` method.

**Comment by nateiler** [comment]
The `Swift_Mime_Message` class also changed to `Swift_Mime_SimpleMessage`.  I have a pull request #13 which brings compatibility for Swift Mailer 6.  Admittedly, I couldn't find a 'ping' reference in their API.

**Comment by atheken** [comment]
Hi folks, thanks for the PR. I’ll review it and merge it this week if everything looks good.

//Andrew

**Comment by alsar** [comment]
@atheken did you had the time to review this PR?

**Comment by colindecarlo** [comment]
I've opened a separate PR (https://github.com/wildbit/swiftmailer-postmark/pull/14) using the work that @nateiler did as a jumping off point (thanks).

The tests run and build is now passing again. I suspect this will require a major version change considering support for Swift Mailer v6 drops support for php versions less than 7.0 and hhvm.

If there is anything else I can do to help move this along please let me know.

**Comment by brandonkelly** [comment]
@colindecarlo 

> I suspect this will require a major version change considering support for Swift Mailer v6 drops support for php versions less than 7.0 and hhvm.

Swiftmailer’s composer requirements specify that it requires PHP 7+, so Composer won’t install it on systems with < PHP 7 anyway. So the PHP change doesn’t _mandate_ a major version bump in your package. (Plenty of other packages will bump the PHP version requirement independently of major versions.)

**Comment by colindecarlo** [comment]
Even better.

**Comment by atheken** [comment]
Hey all. Closing this up, as I've just released version 3 of the transport with SwiftMailer 6 support.

Please let us know if you run into issues or have questions.
