### ISSUE TITLE
Support Guzzle 7

### ISSUE THREAD

**Issue by jesperbjerke** [wildbit/swiftmailer-postmark#30]
It was just released, but creating an issue to raise awareness :)

**Comment by mfn** [comment]
See https://github.com/wildbit/swiftmailer-postmark/pull/27

**Comment by mfn** [comment]
And now see https://github.com/wildbit/swiftmailer-postmark/pull/37

**Comment by vladsandu** [comment]
@jesperbjerke this was fixed in release version 3.3.0.
