### ISSUE TITLE
Does not work with Laravel 8 (Guzzle 7)

### ISSUE THREAD

**Issue by jefferson333** [wildbit/swiftmailer-postmark#38]
composer require wildbit/swiftmailer-postmark

Using version ^3.2 for wildbit/swiftmailer-postmark
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - wildbit/swiftmailer-postmark 3.2.0 requires guzzlehttp/guzzle ^6.0.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for wildbit/swiftmailer-postmark ^3.2 -> satisfiable by wildbit/swiftmailer-postmark[3.2.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by mfn** [comment]
Lobby for https://github.com/wildbit/swiftmailer-postmark/pull/37 and a release!

**Comment by vladsandu** [comment]
@jefferson333 this was fixed in release version 3.3.0.
