### ISSUE TITLE
Wrong return type for send function

### ISSUE THREAD

**Issue by iveretelnyk** [wildbit/swiftmailer-postmark#7]
The definition of Swift_Transport->send function requires  to return int. You return result of http client call. 
When sending symfony do this

 $count += $transport->send($message, $failedRecipients); 

With your implementation it will cause 

Notice: Object of class GuzzleHttp\Psr7\Response could not be converted to int

**Comment by atheken** [comment]
@iveretelnyk Hmm, OK, thanks for the heads-up. We'll get this fixed.

**Comment by darkbluesun** [comment]
@atheken when will you be fixing this?

**Comment by atheken** [comment]
This should be resolved with the latest release. Thanks for bringing it to our attention, and I'm sorry for the incredibly long delay in resolving it.
