### ISSUE TITLE
text/plain body is not sent using setBody()

### ISSUE THREAD

**Issue by z38** [wildbit/swiftmailer-postmark#8]
During testing, we discovered that a `text/plain` body is not sent whenever an additional part is added to the message later on.

Example (taken from [Swiftmailer docs](http://swiftmailer.org/docs/messages.html)):
```
$message = Swift_Message::newInstance()
    ->setSubject('Your subject')
    ->setFrom(array('john@doe.com'))
    ->setTo(array('receiver@domain.org'))
    ->setBody('Here is the message itself', 'text/plain')
    ->addPart('<q>Here is the message itself</q>', 'text/html')
;
```

At the moment the transport just assumes that the main body of any multipart message is `text/html`. It seems this issue can not be resolved just yet, as the content type of the body is not exposed: swiftmailer/swiftmailer#736

As a workaround, we use `setBody` for HTML and `addPart` for text. The parts get reordered anyway.

**Comment by atheken** [comment]
Hi @z38 - Thanks for the info. If I'm reading this correctly, there's nothing we can do about this, as it's an issue in how Swiftmailer handles single body parts? If there's something we can do to improve this, let me know, otherwise, I'm going to mark this issue as closed.

**Comment by yareckon** [comment]
Added a pull request to at least expose that Body value so you can do your own workaround #939
